// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: defs.proto

package linestogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Layers []*Layer `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_defs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_defs_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Page) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type Layer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strokes []*Stroke `protobuf:"bytes,1,rep,name=strokes,proto3" json:"strokes,omitempty"`
}

func (x *Layer) Reset() {
	*x = Layer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_defs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_defs_proto_rawDescGZIP(), []int{1}
}

func (x *Layer) GetStrokes() []*Stroke {
	if x != nil {
		return x.Strokes
	}
	return nil
}

type Stroke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pen         uint32     `protobuf:"varint,1,opt,name=pen,proto3" json:"pen,omitempty"`
	StrokeColor uint32     `protobuf:"varint,2,opt,name=stroke_color,json=strokeColor,proto3" json:"stroke_color,omitempty"`
	PenWidth    float32    `protobuf:"fixed32,3,opt,name=pen_width,json=penWidth,proto3" json:"pen_width,omitempty"`
	Segments    []*Segment `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *Stroke) Reset() {
	*x = Stroke{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stroke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stroke) ProtoMessage() {}

func (x *Stroke) ProtoReflect() protoreflect.Message {
	mi := &file_defs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stroke.ProtoReflect.Descriptor instead.
func (*Stroke) Descriptor() ([]byte, []int) {
	return file_defs_proto_rawDescGZIP(), []int{2}
}

func (x *Stroke) GetPen() uint32 {
	if x != nil {
		return x.Pen
	}
	return 0
}

func (x *Stroke) GetStrokeColor() uint32 {
	if x != nil {
		return x.StrokeColor
	}
	return 0
}

func (x *Stroke) GetPenWidth() float32 {
	if x != nil {
		return x.PenWidth
	}
	return 0
}

func (x *Stroke) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Speed     float32 `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Width     float32 `protobuf:"fixed32,4,opt,name=width,proto3" json:"width,omitempty"`
	Direction float32 `protobuf:"fixed32,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Pressure  float32 `protobuf:"fixed32,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_defs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_defs_proto_rawDescGZIP(), []int{3}
}

func (x *Segment) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Segment) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Segment) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Segment) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Segment) GetDirection() float32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *Segment) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

type RawPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page []byte `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *RawPage) Reset() {
	*x = RawPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPage) ProtoMessage() {}

func (x *RawPage) ProtoReflect() protoreflect.Message {
	mi := &file_defs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPage.ProtoReflect.Descriptor instead.
func (*RawPage) Descriptor() ([]byte, []int) {
	return file_defs_proto_rawDescGZIP(), []int{4}
}

func (x *RawPage) GetPage() []byte {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_defs_proto protoreflect.FileDescriptor

var file_defs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x74, 0x6f, 0x67, 0x6f, 0x22, 0x48, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74,
	0x6f, 0x67, 0x6f, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x22, 0x34, 0x0a, 0x05, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x74,
	0x72, 0x6f, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x74, 0x6f, 0x67, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x52, 0x07,
	0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x6f,
	0x6b, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x70, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x5f, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x6f,
	0x6b, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x6e, 0x5f, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x65, 0x6e, 0x57,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x6f,
	0x67, 0x6f, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75,
	0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75,
	0x72, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x61, 0x77, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x77, 0x75, 0x6c, 0x76, 0x65, 0x72, 0x79, 0x63, 0x6b, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x74, 0x6f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_defs_proto_rawDescOnce sync.Once
	file_defs_proto_rawDescData = file_defs_proto_rawDesc
)

func file_defs_proto_rawDescGZIP() []byte {
	file_defs_proto_rawDescOnce.Do(func() {
		file_defs_proto_rawDescData = protoimpl.X.CompressGZIP(file_defs_proto_rawDescData)
	})
	return file_defs_proto_rawDescData
}

var file_defs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_defs_proto_goTypes = []interface{}{
	(*Page)(nil),    // 0: linestogo.Page
	(*Layer)(nil),   // 1: linestogo.Layer
	(*Stroke)(nil),  // 2: linestogo.Stroke
	(*Segment)(nil), // 3: linestogo.Segment
	(*RawPage)(nil), // 4: linestogo.RawPage
}
var file_defs_proto_depIdxs = []int32{
	1, // 0: linestogo.Page.layers:type_name -> linestogo.Layer
	2, // 1: linestogo.Layer.strokes:type_name -> linestogo.Stroke
	3, // 2: linestogo.Stroke.segments:type_name -> linestogo.Segment
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_defs_proto_init() }
func file_defs_proto_init() {
	if File_defs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_defs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stroke); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_defs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_defs_proto_goTypes,
		DependencyIndexes: file_defs_proto_depIdxs,
		MessageInfos:      file_defs_proto_msgTypes,
	}.Build()
	File_defs_proto = out.File
	file_defs_proto_rawDesc = nil
	file_defs_proto_goTypes = nil
	file_defs_proto_depIdxs = nil
}
